services:
  kanban-viewer:
    image: kanban-viewer
    build:
      context: ../..
      dockerfile: packages/kanban-viewer/Dockerfile
    container_name: kanban-viewer
    ports:
      - "5566:3000"
    volumes:
      - ./prisma/data:/app/prisma/data
    restart: unless-stopped
